import { FC } from "react";
import { BsInfoCircle } from "react-icons/bs";

import Panel from "./Panel";

const DescriptionPanel: FC = () => {
  return (
    <Panel
      initiallyDeployed
      title={
        <>
          <BsInfoCircle className="text-muted" /> Description
        </>
      }
    >
      <p>
        This map represents a <i>network</i> of measured concepts on human flourishing, broadly defined. Each{" "}
        <i>node</i> represents a concept or term, and each edge a{" "}
        <i>link</i> between them.
      </p>
      <p>
        The links are generated by assuming that concepts that appear in the same
        measurement item, subscale, or scale are related. Consistent with this, items
        in scales correlate by 0.4 - 0.7.
      </p>
      <p>
        Nodes sizes are related to their{" "}
        <a target="_blank" rel="noreferrer" href="https://en.wikipedia.org/wiki/Betweenness_centrality">
          weighted degree
        </a>
        , the sum of their link weights.
        Global terms, like <i>Well-being</i>, have been omitted.
        For clarity, only 50% of the edges in the full network are included here.
      </p>
      <p>
        This web application has been developed by{" "}
        <a target="_blank" rel="noreferrer" href="https://reubenrusk.com/">
          Reuben Rusk
        </a>
        , using{" "}
        <a target="_blank" rel="noreferrer" href="https://reactjs.org/">
          React
        </a>{" "}
        based on the{" "}
        <a target="_blank" rel="noreferrer" href="https://www.sigmajs.org">
          sigma.js{" "}
        </a>
        package. You can read the source code{" "}
        <a target="_blank" rel="noreferrer" href="https://github.com/openflourishing">
          on GitHub
        </a>
        .
      </p>
    </Panel>
  );
};

export default DescriptionPanel;
